# Generated by Django 4.0.4 on 2022-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
