# Generated by Django 4.0.4 on 2022-07-07 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
