# Generated by Django 4.0.4 on 2022-07-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invite_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
