# Generated by Django 4.0.4 on 2022-06-22 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_anchorinvite_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('declined', 'declined'), ('expired', 'expired'), ('canceled', 'canceled')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
                ('passer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passer_anchor_table', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_anchor_table', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skill')),
            ],
            options={
                'unique_together': {('receiver_email', 'skill')},
            },
        ),
        migrations.RemoveField(
            model_name='anchortable',
            name='level',
        ),
        migrations.RemoveField(
            model_name='anchortable',
            name='passer',
        ),
        migrations.RemoveField(
            model_name='anchortable',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='anchortable',
            name='skill',
        ),
        migrations.DeleteModel(
            name='AnchorInvite',
        ),
        migrations.DeleteModel(
            name='AnchorTable',
        ),
    ]
