# Generated by Django 4.0.4 on 2022-06-22 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_anchor_remove_anchortable_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_anchor_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
