# Generated by Django 4.0.4 on 2022-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_anchor_status_alter_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('declined', 'declined'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='pending', max_length=120),
        ),
    ]
