# Generated by Django 4.0.4 on 2022-07-08 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invite_accepted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_anchor_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anchor',
            unique_together={('passer', 'receiver', 'skill')},
        ),
        migrations.AddField(
            model_name='anchor',
            name='receiver_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.invite'),
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='receiver_email',
        ),
    ]
