# Generated by Django 4.0.4 on 2022-07-12 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_invite_code'),
        ('main', '0014_alter_anchor_level_alter_assessment_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anchor',
            unique_together={('passer', 'receiver_invite', 'skill')},
        ),
    ]
